### ISSUE TITLE
syzoj-renderer 有点奇怪

### ISSUE THREAD

**Issue by fearlessxjdx** [syzoj/syzoj#101]
```plain
##### 题目名称
> 如果是原题照搬，就按原题题目。格式:「题目来源」题目名称    例如:「NOIP2009提高组」最优贸易

> 如果是自出题目，题目需和题意有相关性。格式:「原创」题目名称
```
渲染结果:
![image](https://user-images.githubusercontent.com/17431574/54905473-10243e00-4f1c-11e9-83cf-a603874c2222.png)

出现了多个框

**Comment by xmcp** [comment]
> ##### 题目名称
> > 如果是原题照搬，就按原题题目。格式:「题目来源」题目名称    例如:「NOIP2009提高组」最优贸易
>
> > 如果是自出题目，题目需和题意有相关性。格式:「原创」题目名称

↑ 瞧，似乎本来就应该有两个框

**Comment by fearlessxjdx** [comment]
> > ##### 题目名称
> > > 如果是原题照搬，就按原题题目。格式:「题目来源」题目名称    例如:「NOIP2009提高组」最优贸易
> > 
> > 
> > > 如果是自出题目，题目需和题意有相关性。格式:「原创」题目名称
> 
> ↑ 瞧，似乎本来就应该有两个框

```plain
##### 题目名称
> 如果是原题照搬，就按原题题目。格式:「题目来源」题目名称    例如:「NOIP2009提高组」最优贸易
> 如果是自出题目，题目需和题意有相关性。格式:「原创」题目名称
```
这是我想实现的，但syzoj上不能这样写，所以写了个空行

**Comment by Menci** [comment]
```markdown
##### 题目名称
> 如果是原题照搬，就按原题题目。格式:「题目来源」题目名称    例如:「NOIP2009提高组」最优贸易
>
> 如果是自出题目，题目需和题意有相关性。格式:「原创」题目名称
```

##### 题目名称
> 如果是原题照搬，就按原题题目。格式:「题目来源」题目名称    例如:「NOIP2009提高组」最优贸易
>
> 如果是自出题目，题目需和题意有相关性。格式:「原创」题目名称
