### ISSUE TITLE
Feature request: Customize the Clang_Format option.

### ISSUE THREAD

**Issue by iftest614** [syzoj/syzoj#108]
As we know, Clang_Format has multiple styles to choose, Like LLVM, Google, Mozilla, Webkit, Visual Studio, etc. Further more, Clang_Format also support `.clang_format` to choose personalise code formatting options. Could we have a radio on the user_edit page let user to choose their own format option?

**Comment by Menci** [comment]
To save server's resource, SYZOJ's code formatting is processed when code is submitted, and sent to browser whenever needed. Adding options for every user to customize it needs code to be re-formatted every time it shows. It costs much more and become DoS vulnerable.

**Comment by iftest614** [comment]
Right. That's indeed a key problem. How about change the default format config? I think the default config (LLVM?confused.) are inconvenient to read, at least for the olympic code. May we can use other style like Visual Studio or Mozilla, or write `.clang_format` .

**Comment by Menci** [comment]
You can modify the code in `lib/code_format.js` to achieve it. But why the current config is inconvenient to read?

**Comment by iftest614** [comment]
Ok, thanks. 

I don't know how to descibe it exactly, May just because the olympic code are most likely to be compact and short? I think the right space is necessary, but can’t stand the braces without wrap. Code with wrap after braces could be more easier to read...
