### ISSUE TITLE
无法正常运行使用 testlib.h 的SPJ

### ISSUE THREAD

**Issue by mektpoy** [syzoj/syzoj#109]
尝试import了`https://loj.ac/problem/6090`这题，交了一份AC的代码，返回`Judgement Failed`

其中测试点的SPJ信息为：`Special Judge returned an unrecoginzed score: .`

**Comment by mektpoy** [comment]
把`#include "testlib.h"`替换成`loj.ac`提供的`testlib.h`的整个内容倒是勉强能正常用着，但太鬼畜了…

**Comment by Menci** [comment]
Sandbox version 181202's `testlib.h` is broken. Not a bug of SYZOJ.
