### ISSUE TITLE
Can't run syzoj-judge normally

### ISSUE THREAD

**Issue by GQH123** [syzoj/syzoj#11]
As the title says : 
![default](https://user-images.githubusercontent.com/26428685/28476293-1abc84d4-6e82-11e7-9549-b5fc6297e072.png)

**Comment by dramforever** [comment]
手动将 [package.json](https://github.com/syzoj/syzoj-judge/blob/master/package.json#L7) 中的 `--harmony-async-await` 删掉

**Comment by GQH123** [comment]
那么，如何进行评测呢，我先运行syzoj然后运行了syzoj-judge，但是评测还是没有什么反应 @dramforever

**Comment by Menci** [comment]
这个 repo 已经过时了，请使用 syzoj-judge2
