### ISSUE TITLE
There's something wrong when I add problems

### ISSUE THREAD

**Issue by GQH123** [syzoj/syzoj#12]
As the title says : 
![default](https://user-images.githubusercontent.com/26428685/28476491-c1ff8e1c-6e82-11e7-84a3-f60f06a2dd55.png)

As long as I add a problem, it will be thrown, so I have to restart syzoj again and again...

By the way , how to add problems in large quantities, which means I can add many problems within a single operation?

**Comment by dramforever** [comment]
请安装 p7zip

**Comment by GQH123** [comment]
然而已经安装了p7zip... @dramforever

**Comment by Menci** [comment]
p7zip-full
