### ISSUE TITLE
迁移后计算 rating 时出错

### ISSUE THREAD

**Issue by asdfghjil** [syzoj/syzoj#126]
计算 rating 时出现如下问题：

![image](https://user-images.githubusercontent.com/50292218/57192891-220bee80-6f68-11e9-94dc-19b347da970c.png)

数据库中出现 `contest_id` 为 `NULL` 的情况。

![image](https://user-images.githubusercontent.com/50292218/57192908-51baf680-6f68-11e9-8481-0c84304650c5.png)

**Comment by Menci** [comment]
Closed via #133.
