### ISSUE TITLE
Need Help with config.json

### ISSUE THREAD

**Issue by WaterWan** [syzoj/syzoj#13]
I copied config.json and here I use mysql in my computer , and my username and password are as follows:  
"db": {
    "database": "mysql",
    "username": "root",
    "password": "",
    "host": "127.0.0.1",
    "dialect": "sqlite",
    "storage": "syzoj.db"
  },
I still install sqlite3 as well, but my version is 3.19.3. Now the console tells me that " Error: Please install sqlite3 package manually". Does it make sense? Should I reinstall sqlite with another version?
Alse, what site should I visit after I run app.js?
Thank you! @Menci

**Comment by Menci** [comment]
Your `sqlite3` isn't installed properly.
Maybe the network error occurred when downloading the `sqlite3`'s native addon.

Please `cd node_modules/sqlite3` and `npm run install`.
