### ISSUE TITLE
比赛初始化可能存在问题

### ISSUE THREAD

**Issue by Kanaricc** [syzoj/syzoj#130]
在contest创建时，似乎没有初始化ranklist的ranklist，导致访问比赛出错。

TypeError: Cannot read property 'player_num' of null

**Comment by lamhaoyin2** [comment]
![屏幕截图(8)](https://user-images.githubusercontent.com/46623537/57272335-e129ec00-70c5-11e9-9150-ec3f302f656d.png)

像是这样，希望能够有所帮助（

**Comment by cqnuljs** [comment]
`node migrates/build-statistics.js｀ 这条命令执行没？

**Comment by lamhaoyin2** [comment]
> `node migrates/build-statistics.js` 这条命令执行没？

刚去执行了下，然而并没有效果

**Comment by Menci** [comment]
```mysql
USE syzoj
UPDATE contest_ranklist SET ranklist = '{"player_num":0}' WHERE ranklist IS NULL;
```
