### ISSUE TITLE
测试数据下载问题

### ISSUE THREAD

**Issue by cqnuljs** [syzoj/syzoj#131]
![databug.png](https://i.loli.net/2019/05/08/5cd2edb5467b9.png)

下载完整数据包出错，数据不是本题的，另外单个测试点的文件下载没问题。

**Comment by Menci** [comment]
你是不是绕过 web 自己操作了测试数据

**Comment by cqnuljs** [comment]
嗯，是的

**Comment by cqnuljs** [comment]
已经处理好了，有方法直接操作数据吗？
