### ISSUE TITLE
比赛提交后显示“当前比赛中无此题目”

### ISSUE THREAD

**Issue by hankeke303** [syzoj/syzoj#132]
大概查了一下是因为

![image](https://user-images.githubusercontent.com/28253614/57580522-42dec180-74dd-11e9-8efe-8e46e340857f.png)

这句话里面的 `problems` 的每一个元素都是 `number` 类型的，但是 `judge_state.problem_id` 不知道为什么变成了 `string` 类型？？？

似乎是因为

![image](https://user-images.githubusercontent.com/28253614/57580534-833e3f80-74dd-11e9-8216-696384e1760e.png)

里面的 `req.params.id` 是 `string` 类型的，所以就会把 `judge_state.problem_id` 变成了 `string` 类型。

把这里的 `req.params.id` 改成 `id` 或者把之前的 `!problems.includes(judge_state.problem_id)` 改成 `!problems.includes(parseInt(judge_state.problem_id))` 都没有问题了。

但是不知道为什么以前不会出现这个问题。

另外，似乎比赛中每一个人第一次提交的时候并不会自动向 `contest_player` 中插入一行数据？？？所以会出现 `TypeError: Cannot read property '1' of undefined`。

**Comment by Menci** [comment]
可以提个 pull request

最近的重构没有测比赛，所以出了不少锅 ……

**Comment by Menci** [comment]
Closed via #133
