### ISSUE TITLE
功能请求：用户分为：学生用户（+分组）和教师用户

### ISSUE THREAD

**Issue by youyukyc** [syzoj/syzoj#137]
1、自己搭建OJ后，可能有多个老师使用一个OJ，这时候新建的比赛，都可以看到，比较混。
【是否可以，让对应学生用户，只看到自己老师的比赛（比赛分为：我的比赛和公开比赛两项）】
2、一个老师，可能带不同层次的几批学生，低层次的学生暂时完成不了高层次的人。
【是否可以，让学生优先查看符合自己层级的比赛，便于练习管理】

**Comment by Menci** [comment]
没有这方面的计划
