### ISSUE TITLE
monaco-editor

### ISSUE THREAD

**Issue by SchrodingerZhu** [syzoj/syzoj#14]
Is it possible to add Microsoft's [monaco-editor](https://microsoft.github.io/monaco-editor/index.html) to our submitting page?

**Comment by Menci** [comment]
Possible but why?

**Comment by SchrodingerZhu** [comment]
Coding Platforms like TopCoder have full featured editor, so I just suggest ...

**Comment by xmcp** [comment]
`monaco-editor` only has "Basic Syntax Colorization" for most languages inlcuding C/C++.

So it is nothing better than Ace, the current editor.
