### ISSUE TITLE
功能请求：更细致的比赛排行榜

### ISSUE THREAD

**Issue by youyukyc** [syzoj/syzoj#141]
建议比赛排行榜显示，首次提交成绩-最高分-提交次数（还可以加，最快AC时间，最少内存程序）

以引导学生，深度思维，而不是把loj作为测试系统，一条条，下载测试，刷过去。思维深度不够。

**Comment by Menci** [comment]
暂时没有这样的计划

**Comment by youyu** [comment]
能不能，知道下，要修改的文件，自学尝试下，不熟悉nodejs
