### ISSUE TITLE
关于格式化代码的问题

### ISSUE THREAD

**Issue by rsj001** [syzoj/syzoj#144]
在提交页面代码显示高亮，但在评测页面和题面中不显示高亮。
曾运行过_yarn add pygmentize_,没有任何作用
![aa](https://user-images.githubusercontent.com/46622836/58368674-d1623280-7f22-11e9-99e9-a6425fce14fe.png)
![bb](https://user-images.githubusercontent.com/46622836/58368675-d1fac900-7f22-11e9-9f1d-8ed89a8b5dee.png)

**Comment by rsj001** [comment]
请问这该如何解决

**Comment by Menci** [comment]
`pip install pygments`

pygments 是个 python 包 ……

**Comment by rsj001** [comment]
hi？
还是不行啊

**Comment by rsj001** [comment]
安装过了没有任何效果

**Comment by rsj001** [comment]
还是无法格式化

**Comment by rsj001** [comment]
怀疑是Markdown版本问题

**Comment by rsj001** [comment]
在代码后加一个回车就行了
为什么以前没有这个问题？ @Menci

**Comment by rsj001** [comment]
？？？

**Comment by Kewth** [comment]
我也碰到了不能高亮的问题。。

**Comment by cqnuljs** [comment]
在 `/opt/syzoj/web` 执行一下 `yarn` ，然后重启 web 端，@rsj001
