### ISSUE TITLE
注销不了

### ISSUE THREAD

**Issue by cqnuljs** [syzoj/syzoj#146]
刚更新的版本，用户注销不了？求救

**Comment by cqnuljs** [comment]
`cd /opt/syzoj-web && node app.js ` 这样子注销又是没问题的~

**Comment by Menci** [comment]
你是不是以 root 运行过 `node app.js`？如果有的话以 `syzoj` 用户重建 `sessions` 文件夹。

**Comment by cqnuljs** [comment]
运行过的，谢谢~
