### ISSUE TITLE
代码高亮问题&分布式评测问题

### ISSUE THREAD

**Issue by rsj001** [syzoj/syzoj#148]
1.为什么我的OJ 代码只有在特定格式下才能高亮？
我写

\`\`\`cpp
int get_num();
int guess(int index, int x);
void submit(const std::vector<int> &resultv);
\`\`\`

就不会高亮
但是
\`\`\`cpp
int get_num ();
int guess (int index, int x);
void submit (const std::vector<int> &resultv);
\`\`\`
就会高亮（注意函数名和参数之间多了一个空格）
<img width="690" alt="a" src="https://user-images.githubusercontent.com/46622836/58742892-81bbc380-845a-11e9-8256-f1d83a7a7bfd.png">
pip install pygments     pip3 install pygments 等都试过了还是如此

2.分布式评测时会出现SystemError，FileError，应该是多线程同时占用某个文件的问题，该如何解决？

P.S.作者什么时候更新多评测机的多线程评测...

**Comment by rsj001** [comment]
@Menci  对不起，那个问题还没有解决

**Comment by Menci** [comment]
![image](https://user-images.githubusercontent.com/11341955/58743033-e9730e00-845c-11e9-80da-80430985a2c6.png)

我这里很正常

**Comment by Menci** [comment]
分布式评测需要你把每个的 cgroup 名称设置为不同的，并且用不同的临时目录，要不然就会冲突

**Comment by rsj001** [comment]
好的
可我的代码高亮就是不行 \笑哭

**Comment by rsj001** [comment]
重装是万能的？？好了？？
