### ISSUE TITLE
启动评测端systemd问题

### ISSUE THREAD

**Issue by liuyi585851** [syzoj/syzoj#149]
![image](https://user-images.githubusercontent.com/39161527/58759282-f164a800-8559-11e9-8e6c-3fdbb8a78e27.png)
请问下启动syzoj-judge-runner.service时提示上图信息怎么办？

**Comment by Menci** [comment]
请发一下详细的错误信息

**Comment by liuyi585851** [comment]
问题已解决，是安装RabbitMQ未重启导致的。
顺便请问下syzoj-judge-runner与daemon有何区别？应该启动哪个？
我这边启动runner没有反应，只有启动daemon才能正常评测。
非常感谢!

**Comment by Menci** [comment]
都要启动。
