### ISSUE TITLE
编辑题目描述时使用 Ace Editor

### ISSUE THREAD

**Issue by xmcp** [syzoj/syzoj#15]
反正 Ace Editor 也支持 Markdown，在写题面的时候，弄个带语法高亮的编辑器肯定比现在这个裸的 textarea 爽多了。

唯一的缺点就是 Ace Editor 的 Markdown 高亮好像不支持 `$公式$`，不过无论如何都比现在好使。

**Comment by Menci** [comment]
ACE 确实是这个问题 ……

我之前开发 Moeditor 的时候把 CodeMirror 的 $ 支持做了，我去看看 ACE 好不好弄。

**Comment by Menci** [comment]
我最近也不怎么有时间了 …… 要不要你去看看啊 ……

**Comment by xmcp** [comment]
我也没什么时间啊……

稍微改了一下，大概像这样？

![image](https://user-images.githubusercontent.com/6646473/29250214-0d4547b8-8071-11e7-9755-c395fb8f0c4d.png)

（`$` 的配色挺丑的，但我也不知道什么颜色好看）

**Comment by xmcp** [comment]
https://github.com/xmcp/ace/commit/0a3b3a026406c681bf6b7b638036ff0d9cb6b3e6

魔改了 `markdown_highlight_rules.js`，支持 `$公式$` 语法，`$` 的配色在129和211行，你觉得不爽就看着改吧。

我没有 nodejs 环境，所以不保证能用 :roll_eyes:

**Comment by Menci** [comment]
还有

```
$$
f(x) = x + 1
$$
```

这种语法

**Comment by xmcp** [comment]
https://github.com/xmcp/ace/tree/47f16f9ed51923736eac5540d97eb3bbb630ff98

公式块的 highlight rule 和 folding 都加上了。
