### ISSUE TITLE
请问能否提供一下向评测机同步测试数据的思路

### ISSUE THREAD

**Issue by asdfghjil** [syzoj/syzoj#152]
因为有一台机器适合做服务器，还有一台适合做评测机，所以想将服务端和评测端运行在不同的机器上，能否提供一下同步测试数据的思路？

PS：请问 wiki 里面的多评测机什么时候才能写好啊？

**Comment by lifanisagoodboy** [comment]
就是啊，学校OJ急迫需要分布式测评啊。。。。

**Comment by Menci** [comment]
loj 是用跑了个脚本检测到文件变化就 rsync

**Comment by lifanisagoodboy** [comment]
明白啦，感谢menci，最爱这套oj了，谢谢它帮助我们在csp中取得了不错的成绩。。哈哈，周末愉快。

在 2019-12-14 20:18:09，"Menci" <notifications@github.com> 写道：


loj 是用跑了个脚本检测到文件变化就 rsync
