### ISSUE TITLE
用户可通过直接修改cookie达到伪造身份

### ISSUE THREAD

**Issue by pandadtdyy** [syzoj/syzoj#154]
登录直接通过json存入cookie未加密导致用户可以直接伪造cookie来获得管理员身份

**Comment by pandadtdyy** [comment]
数据库存放用户名以及其密码MD5，cookie也通过用户名及其密码MD5构造，等同于能查看数据库表的人可以随意构造cookie登陆他人账号

**Comment by Wycers** [comment]
我可以确定这个bug存在

**Comment by asdfghjil** [comment]
都有数据库权限了为什么还需要构造cookie登陆

**Comment by Wycers** [comment]
> 都有数据库权限了为什么还需要构造cookie登陆

比如说只拥有数据库读权限的管理员登录后可以修改一些东西，相当于获得了部分写权限

**Comment by Menci** [comment]
#45
