### ISSUE TITLE
话说这东西怎么安装到本地呀

### ISSUE THREAD

**Issue by icyskyair** [syzoj/syzoj#16]
如题

**Comment by Ir1d** [comment]
https://github.com/syzoj/syzoj#deploying

**Comment by zryoung** [comment]
虽然看了Deploying。但还是不会安装。
比如：Install dependencies with npm install or yarn. Also, follow the instructions here to install 7z executable used by the node-7z package.

Copy config-example.json to config.json, and make necessary changes.
搞不懂。linux及服务器相关的都不懂

所以，有没有更详细的安装文档？谢谢。
