### ISSUE TITLE
询问各位大佬们怎么安装syzoj啊！

### ISSUE THREAD

**Issue by chihuo2104** [syzoj/syzoj#164]
# 看不懂Wiki，只好求教大佬

**Comment by Phemon** [comment]
**去开发群里**提出**更具体的问题**而不是问“怎么安装”或许可以对你有帮助。在这里发 issue 来问如何安装或许只能得到 RTFM/STFW 的回答。

**Comment by chihuo2104** [comment]
> **去开发群里**提出**更具体的问题**而不是问“怎么安装”或许可以对你有帮助。在这里发 issue 来问如何安装或许只能得到 RTFM/STFW 的回答。

# 开发群是啥(大雾)

**Comment by Phemon** [comment]
> > **去开发群里**提出**更具体的问题**而不是问“怎么安装”或许可以对你有帮助。在这里发 issue 来问如何安装或许只能得到 RTFM/STFW 的回答。
> 
> # 开发群是啥(大雾)

加入 QQ 群 565280992 或 Telegram 群 @lojdev 以取得帮助。

**Comment by Phemon** [comment]
如果你解决了问题或者放弃了安装 SYZOJ ，或许你可以考虑 close 掉这个 issue 。

**Comment by chihuo2104** [comment]
放弃了，换UOJ QAQ
