### ISSUE TITLE
Article replies send at the same time count only once.

### ISSUE THREAD

**Issue by 2403772980ygy** [syzoj/syzoj#166]
If 2 replies of an article is send at the same time, the counter will treat them as one. Then if you delete them all, the reply count can be negative.

**Comment by Phemon** [comment]
1.  Does "2 replies of an article are sent at the same time" means to clink the "Reply" button twice in a short time ? I can't reproduce it with my own latest version of SYZOJ now.
2.  Have you tried "Recalculate the discussions number and time" at ``/admin/other``?

**Comment by 2403772980ygy** [comment]
Cannot reproduce now, but don't get when will this happen. It seems to be a temporary bug.

**Comment by cqnuljs** [comment]
me too
