### ISSUE TITLE
Forbidden问题

### ISSUE THREAD

**Issue by CommonAnts** [syzoj/syzoj#17]
某些浏览器（例如360）在提交题目时会出错并显示Forbidden，求解决……

**Comment by xmcp** [comment]
建议提供问题的精确复现步骤和浏览器版本号。

**Comment by CommonAnts** [comment]
例如，使用基于Chromium的世界之窗浏览器（版本 7.0.0.108 内核版本： 48.0.2564.116），进入任意题目提交界面（如 https://loj.ac/problem/1#submit_code），在框中输入任意语言任意代码单击提交，就会跳转到显示“Forbidden”的错误界面（地址栏是 https://loj.ac/problem/1/submit）；如果改用文件提交，就会没反应。

**Comment by xmcp** [comment]
大概找到问题了：

`addUrlParam` 函数用了 `for(let x in ...)` 语法，所以不支持的浏览器在这行就崩掉了：

```javascript
$('form').each(function () {
  this.action = addUrlParam(this.action || location.href, '_csrf', document.head.getAttribute('data-csrf-token'));
});
```

于是提交代码那个表单的 CSRF Token 就没加上，然后就 403 了。

解决方案：不想上 Babel 就别用那么风骚的 ES6 写法。

**Comment by dramforever** [comment]
@xmcp 你这出了偏差啊，人家可上 babel 了啊。https://github.com/syzoj/syzoj/blob/master/.babelrc

**Comment by t123yh** [comment]
judge-v3 分支已经解决
