### ISSUE TITLE
评测机一直waiting

### ISSUE THREAD

**Issue by MX-Qulin** [syzoj/syzoj#173]
按照wiki部署后评测一直waiting
已确保:
    redis v=5.0.6
    两个服务都开了
    judge_token写对了

**Comment by Menci** [comment]
请提供 web 和 judge 的 daemon & runner 的 log

最好把 daemon 和 runner 以 `-v` 启动

**Comment by MX-Qulin** [comment]
问题已解决 谢谢你:)
