### ISSUE TITLE
青藤 OJ 违反开源协议

### ISSUE THREAD

**Issue by Prurite** [syzoj/syzoj#176]
http://code.qingtengbc.com/ 该 OJ 不但没有开源甚至去掉了底部的 powered by SYZOJ

**Comment by Prurite** [comment]
@Menci

**Comment by Menci** [comment]
我发邮件联系他们了，等等回复吧

**Comment by Prurite** [comment]
> 
> 
> 我发邮件联系他们了，等等回复吧

有回复吗

**Comment by Menci** [comment]
没有
