### ISSUE TITLE
一直waiting

### ISSUE THREAD

**Issue by zyllpb** [syzoj/syzoj#179]
root@hnist16306:/opt/syzoj# systemctl status hnistoj-web
● hnistoj-web.service - SYZOJ web service
   Loaded: loaded (/lib/systemd/system/hnistoj-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-12-27 13:11:06 CST; 12s ago
 Main PID: 26865 (node)
    Tasks: 16 (limit: 4915)
   CGroup: /system.slice/hnistoj-web.service
           ├─26865 /usr/bin/node /opt/syzoj/web/app.js -c /opt/syzoj/config/web.json
           └─26881 /usr/bin/node /opt/syzoj/web/libs/rendererd redis://127.0.0.1:6379 30000

Dec 27 13:11:08 hnist16306 env[26865]: SYZOJ is listening on 211.69.252.127:80...
Dec 27 13:11:11 hnist16306 env[26865]: {"message":"Judge client /judge#YC1QbWibtcSOjM7wAAAB connected.","level":"info"}
Dec 27 13:11:11 hnist16306 env[26865]: {"message":"Judge client /judge#YC1QbWibtcSOjM7wAAAB emitted waitForTask.","level":"warn"}
Dec 27 13:11:11 hnist16306 env[26865]: (node:26865) UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command 'bzpopmax'
Dec 27 13:11:11 hnist16306 env[26865]:     at parseError (/opt/syzoj/web/node_modules/redis-parser/lib/parser.js:193:12)
Dec 27 13:11:11 hnist16306 env[26865]:     at parseType (/opt/syzoj/web/node_modules/redis-parser/lib/parser.js:303:14)
Dec 27 13:11:11 hnist16306 env[26865]: (node:26865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (
Dec 27 13:11:11 hnist16306 env[26865]: (node:26865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Dec 27 13:11:11 hnist16306 env[26865]: {"message":"Judge client /judge#jrplCNny3gRiqBIuAAAC connected.","level":"info"}
Dec 27 13:11:11 hnist16306 env[26865]: {"message":"Judge client /judge#jrplCNny3gRiqBIuAAAC emitted waitForTask with invalid token.","level":"warn"}

**Comment by zyllpb** [comment]
@Menci

**Comment by t123yh** [comment]
emitted waitForTask with **invalid token**.

**Comment by Menci** [comment]
1. ReplyError: ERR unknown command **'bzpopmax'**
2. emitted waitForTask with **invalid token**

请按照**部署指南**进行操作
