### ISSUE TITLE
无法发布讨论

### ISSUE THREAD

**Issue by zhou-jk** [syzoj/syzoj#180]
在目前的 2019.12.14 版本中发布讨论显示：

```
QueryFailedError: Column count doesn't match value count at row 1
```

回退版本正常

**Comment by Menci** [comment]
回退到哪个版本正常

**Comment by zhou-jk** [comment]
目前回退到版本 Commits on Nov 9, 2019




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Menci"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月13日(星期一) 中午11:45
收件人:&nbsp;"syzoj/syzoj"<syzoj@noreply.github.com&gt;;
抄送:&nbsp;"山容万物，坚如磐石"<2870037012@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [syzoj/syzoj] 无法发布讨论 (#180)




回退到哪个版本正常

**Comment by zhou-jk** [comment]
> 回退到哪个版本正常

目前回退到版本 Commits on Nov 9, 2019
