### ISSUE TITLE
编辑器输入中文时无法显示

### ISSUE THREAD

**Issue by sunyi1018** [syzoj/syzoj#185]
![image](https://user-images.githubusercontent.com/40137262/77269617-5c978a80-6ce4-11ea-8680-3d9f7eff1ca4.png)

**Comment by Menci** [comment]
![image](https://user-images.githubusercontent.com/11341955/77335055-9ad28f80-6d60-11ea-9d84-893e894dcc39.png)

Chrome for Windows 80.0.3987.149 无法复现

**Comment by sunyi1018** [comment]
已解决。（版本问题）旧版本的syzoj使用的是monaco-editor，会出现这个bug，最新版本好像移除了，换成了普通的plain-text
