### ISSUE TITLE
代码无高亮,求教

### ISSUE THREAD

**Issue by Eric-xin** [syzoj/syzoj#188]
![issue.png](https://i.loli.net/2020/08/06/Ral1SjstrZhIUOL.png)

**Comment by cqnuljs** [comment]
安装 pygments。

**Comment by Eric-xin** [comment]
没有解决 安装了还是不行

**Comment by cqnuljs** [comment]
在网页端安装的最前面还有东西呢，你看看都安装了没？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Eric-xin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月10日(星期一) 中午1:26
收件人:&nbsp;&quot;syzoj/syzoj&quot;<syzoj@noreply.github.com&gt;;
抄送:&nbsp;&quot;李军帅&quot;<1364468428@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [syzoj/syzoj] 代码无高亮,求教 (#188)

**Comment by cqnuljs** [comment]
pygmentize 和 clang-format。后面这个呢？
