### ISSUE TITLE
Nginx提示502 Bad Gateway

### ISSUE THREAD

**Issue by Matt22667** [syzoj/syzoj#191]
前台调试syzoj反馈
``
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at RedisClient.on_error (/opt/syzoj/web/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/opt/syzoj/web/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
``
一看redis没启动
于是设置为了开机启动
然后打开网页还是502
这时使用调试模式没有报错
然后再打开网页就有了
网页不是调试模式就无法访问
求助大佬

**Comment by Matt22667** [comment]
检查后发现设置redis开机启动后还是不行 然后再打开前端调试 就能显示网页 为什么不调试不行呢

**Comment by cqnuljs** [comment]
网页没有开机启动吧------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Matt22667&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月19日(星期三) 晚上9:17
收件人:&nbsp;&quot;syzoj/syzoj&quot;<syzoj@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [syzoj/syzoj] Nginx提示502 Bad Gateway (#191)

**Comment by Matt22667** [comment]
@cqnuljs 我使用了systemd设置了开机启动
命令是``systemctl enable syzoj-web``吧

**Comment by Matt22667** [comment]
我觉得还是systemd没配置对
毕竟手动node app.js是可以的

**Comment by Matt22667** [comment]
更新状况：
现在启动后还是502
但是先
``systemctl stop syzoj-web``
再start就能出现

**Comment by cqnuljs** [comment]
你先不要stop，用systemctl status syzoj-web 查看一下。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Matt22667&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月21日(星期五) 中午12:34
收件人:&nbsp;&quot;syzoj/syzoj&quot;<syzoj@noreply.github.com&gt;;
抄送:&nbsp;&quot;李军帅&quot;<1364468428@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [syzoj/syzoj] Nginx提示502 Bad Gateway (#191)

**Comment by Matt22667** [comment]
@cqnuljs 这是提示信息
``syzoj-web.service - SYZOJ web service
   Loaded: loaded (/lib/systemd/system/syzoj-web.service; enabled; vendor preset
   Active: active (running) since Fri 2020-08-21 05:45:27 UTC; 20s ago
 Main PID: 2284 (node)
    Tasks: 18 (limit: 4658)
   CGroup: /system.slice/syzoj-web.service
           ├─2284 /usr/bin/node /opt/syzoj/web/app.js -c /opt/syzoj/config/web.j
           └─2409 /usr/bin/node /opt/syzoj/web/libs/rendererd redis://127.0.0.1:

Aug 21 05:45:27 ojserver2 systemd[1]: Started SYZOJ web service.
Aug 21 05:45:30 ojserver2 env[2284]: SYZOJ is listening on 127.0.0.1:5283...
Aug 21 05:45:33 ojserver2 env[2284]: {"message":"Judge client /judge#r0pyn-_8uCg
Aug 21 05:45:34 ojserver2 env[2284]: {"message":"Judge client /judge#r0pyn-_8uCg
lines 1-13/13 (END)...skipping...
● syzoj-web.service - SYZOJ web service
   Loaded: loaded (/lib/systemd/system/syzoj-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-08-21 05:45:27 UTC; 20s ago
 Main PID: 2284 (node)
    Tasks: 18 (limit: 4658)
   CGroup: /system.slice/syzoj-web.service
           ├─2284 /usr/bin/node /opt/syzoj/web/app.js -c /opt/syzoj/config/web.json
           └─2409 /usr/bin/node /opt/syzoj/web/libs/rendererd redis://127.0.0.1:6379 30000

Aug 21 05:45:27 ojserver2 systemd[1]: Started SYZOJ web service.
Aug 21 05:45:30 ojserver2 env[2284]: SYZOJ is listening on 127.0.0.1:5283...
Aug 21 05:45:33 ojserver2 env[2284]: {"message":"Judge client /judge#r0pyn-_8uCgzSGphAAAA connected.","level":"info"}
Aug 21 05:45:34 ojserver2 env[2284]: {"message":"Judge client /judge#r0pyn-_8uCgzSGphAAAA emitted waitForTask.","level":"warn"}
``

**Comment by Matt22667** [comment]
突然发现又好了

**Comment by Matt22667** [comment]
@cqnuljs  感谢大佬 已解决
