### ISSUE TITLE
比赛功能的bug

### ISSUE THREAD

**Issue by cqnuljs** [syzoj/syzoj#194]
首先你需要新建一个比赛，里面有试题编号为1的题目和编号为1的管理员，
![sendpix8](https://user-images.githubusercontent.com/8781423/96287286-49e3fa80-1014-11eb-9149-1efedd35fe71.jpg)
正常的新建比赛流程走完之后，然后你再点击修改比赛，神奇的一幕就发生了，如下图：
![sendpix10](https://user-images.githubusercontent.com/8781423/96287444-86175b00-1014-11eb-8445-450eb2fe46a5.jpg)
不建议在自己的（或校内）oj尝试，会导致前端显示异常，数据库倒是没啥问题~

**Comment by Menci** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/5211
