### ISSUE TITLE
点击提交按钮后网站端报错

### ISSUE THREAD

**Issue by FZ-c** [syzoj/syzoj#204]
![image](https://user-images.githubusercontent.com/26593764/106273106-1187c580-626d-11eb-85f0-938324ae7d72.png)
点击提交按钮后网站端报错，日志信息如上图。

**Comment by Menci** [comment]
数据库连接有问题，请检查数据库版本（官方支持 MariaDB 10.3）。如果数据库在另外的机器上运行，请检查网络连接状况。
