### ISSUE TITLE
无法编译（没有权限）

### ISSUE THREAD

**Issue by EricNTH080103** [syzoj/syzoj#205]
An error occurred.
Error: Error: Command failed: /bin/chown -R 65534:65534 -- /opt/syzoj/sandbox/tmp1/bin
/bin/chown: changing ownership of '/opt/syzoj/sandbox/tmp1/bin': Operation not permitted

systemctl status:
● syzoj-judge-runner.service - SYZOJ judge runner service
   Loaded: loaded (/etc/systemd/system/syzoj-judge-runner.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2021-02-01 17:30:41 CST; 17s ago
  Process: 13309 ExecStart=/usr/bin/node /opt/syzoj/judge/lib/runner/index.js -s /opt/syzoj/config/runner-shared.json -i /opt/syzoj/config/runner-instance.json 

Feb 01 17:29:17 VM-0-14-ubuntu node[13309]: /bin/chown: changing ownership of '/opt/syzoj/sandbox/tmp1/bin': Operation not permitted
Feb 01 17:29:17 VM-0-14-ubuntu node[13309]:     at ChildProcess.exithandler (child_process.js:299:12)
Feb 01 17:29:17 VM-0-14-ubuntu node[13309]:     at ChildProcess.emit (events.js:193:13)
Feb 01 17:29:17 VM-0-14-ubuntu node[13309]:     at maybeClose (internal/child_process.js:999:16)
Feb 01 17:29:17 VM-0-14-ubuntu node[13309]:     at Socket.stream.socket.on (internal/child_process.js:403:11)
Feb 01 17:29:17 VM-0-14-ubuntu node[13309]:     at Socket.emit (events.js:193:13)
Feb 01 17:29:17 VM-0-14-ubuntu node[13309]:     at Pipe._handle.close (net.js:614:12)
Feb 01 17:30:41 VM-0-14-ubuntu systemd[1]: syzoj-judge-runner.service: Start operation timed out. Terminating.
Feb 01 17:30:41 VM-0-14-ubuntu systemd[1]: syzoj-judge-runner.service: Failed with result 'timeout'.
Feb 01 17:30:41 VM-0-14-ubuntu systemd[1]: Failed to start SYZOJ judge runner service.

node版本11.15.0

**Comment by EricNTH080103** [comment]
现在将service文件中的user和group改成root，情况解决。
但是生产环境中毕竟不可以这么用。

**Comment by t123yh** [comment]
judge 本身就是需要root权限的
