### ISSUE TITLE
NOI版本编译器和Python可用，GNU和Clang编译器不可用

### ISSUE THREAD

**Issue by BurnoutAg7** [syzoj/syzoj#208]
![image](https://user-images.githubusercontent.com/32872775/109169784-20558f80-77bb-11eb-830b-e95992000c80.png)

![image](https://user-images.githubusercontent.com/32872775/109169833-2ba8bb00-77bb-11eb-8c30-c7074bc87745.png)

![image](https://user-images.githubusercontent.com/32872775/109169880-38c5aa00-77bb-11eb-8a0e-0ca0db61decd.png)

如题，一开始我觉得是我权限配置的问题，但是后来发现事情并没有那么简单，只好来求助万能的Menci了（Clang的图和GNU一个结果我就懒得截图了）

![image](https://user-images.githubusercontent.com/32872775/109170200-88a47100-77bb-11eb-989b-4f3f57335e1f.png)

在沙盒中运行Clang的C++会有一个这句话不知道有没有什么对于解决问题的帮助。

UPD：并不影响编译。

三个服务运行过程中均未报告任何异常。

UPD：正在使用`Debian GNU/Linux 10 (buster)`系统。

UPD：Pascal也可以正常使用。

**Comment by Menci** [comment]
chroot 进 sandbox rootfs，随便编译一个 C 文件执行一下：

```bash
gcc test.c -mx32 && ./a.out
```

怀疑你的内核不支持 x32 ABI

**Comment by BurnoutAg7** [comment]
谢谢Menci大佬，确实是内核的问题，滚去修了qaq

**Comment by BurnoutAg7** [comment]
已经修好了，再次感谢Menci大佬（

记录一下解决办法万一下次又脑抽（）：在`/etc/default/grub`中启动命令里加上`syscall.x32=y`
