### ISSUE TITLE
使用user的nameplate属性作为权限题的识别关键字是否可行

### ISSUE THREAD

**Issue by BurnoutAg7** [syzoj/syzoj#217]
请问@Menci鸽鸽这个可不可行呀，我们的校内OJ用的syzoj，老师说不能给所有人都开放数据下载qaq

**Comment by BurnoutAg7** [comment]
算了，已经决定在model里给user添加一个is_vip了（

**Comment by Menci** [comment]
nameplate 其实是一个隐藏 feature，用来给用户的用户名加后缀
