### ISSUE TITLE
建议：限制编译日志的大小

### ISSUE THREAD

**Issue by SnailQWQ** [syzoj/syzoj#223]
建议最好在编译的时候限制一下输出日志的大小，通过某些手段可以实现输出巨大的编译日志，虽然会因为编译时限被 kill ，但是这样几十MB的日志存在服务器上是个很大的浪费……

记录：

<https://loj.ac/s/1227514>

**Comment by SnailQWQ** [comment]
还有[自己include自己](https://loj.ac/s/1227573)，用[#pragma message 输出消息](https://loj.ac/s/1227601)的操作

**Comment by Menci** [comment]
[Image.jpeg]
是有输出信息大小限制的，后面的会截断掉，而且也不会存储

（以及这是旧版 syzoj2 的 repo，现在 loj 不在用这套系统了
________________________________

**Comment by SnailQWQ** [comment]
@Menci 
好的……是这样啊。

**Comment by Menci** [comment]
![image](https://user-images.githubusercontent.com/11341955/129771332-01372aaf-debe-45e5-9a63-2e8c1a9f2f49.png)

我用 Outlook 客户端回复，图没发出来吗 ……
