### ISSUE TITLE
127.0.01可以访问  但是局域网的IP不能访问  请问要更改为0.0.0.0的话  需要调整哪个部位的代码

### ISSUE THREAD

**Issue by xubingod** [syzoj/syzoj#230]
![image](https://user-images.githubusercontent.com/91514008/135037814-c4fcce3f-7f96-419b-b61b-b1fe8a9e7c2e.png)

**Comment by Menci** [comment]
加个 nginx 吧

**Comment by xubingod** [comment]
> 加个 nginx 吧

在宿主机上？我试试

**Comment by xubingod** [comment]
![image](https://user-images.githubusercontent.com/91514008/135051562-d2d77f50-2346-42ea-9307-614416a87c5f.png)
可行  使用nginx作为转发
