### ISSUE TITLE
能否用docker开启并行评测

### ISSUE THREAD

**Issue by azeng233** [syzoj/syzoj#235]
单评测有点慢呀

**Comment by Menci** [comment]
可以在 docker-compose 的配置里把 judge 相关的条目多复制几份，就可以并行评测

**Comment by azeng233** [comment]
我刚去试了一下，感觉评测速度没有变快，还是一个一个评测的，难道是需要多开守护进程deamon吗？
![image](https://user-images.githubusercontent.com/67224979/151307628-bd2ee843-e6a5-4525-b11b-eea2c70c09c4.png)
![image](https://user-images.githubusercontent.com/67224979/151307657-3c789085-f881-4c4c-8830-35c451675a3d.png)
![image](https://user-images.githubusercontent.com/67224979/151307678-6d055ac6-44a8-45af-9643-c48a03711072.png)
我只修改了名称，其他没动。

**Comment by azeng233** [comment]
![image](https://user-images.githubusercontent.com/67224979/151308214-8a3d7eec-221e-4743-8f9d-1305caf20b6a.png)
现在点击评测报错了

**Comment by Menci** [comment]
配置写的没问题，这样会有多个测试点一起运行

**Comment by azeng233** [comment]
okok谢谢
