### ISSUE TITLE
yarn问题

### ISSUE THREAD

**Issue by EndstoneV** [syzoj/syzoj#249]
昨天我开了 issue #247，Menci 说我的网络有问题，但是我别的能打开，就打不开 nodejs.org.
![image](https://user-images.githubusercontent.com/89293705/177466343-7f36076d-a10e-4d5d-98e8-703de8dea8ee.png)

我找到了一个替代链接，怎么把 yarn 的下载链接换成这个或者把这个文件放到某些位置代替 yarn 的下载（可能和 syzoj 无关 但是百度搜不到，我加群的申请一直没通过，无奈在这里问）
![无标题](https://user-images.githubusercontent.com/89293705/177444947-29f7ab1c-644c-4239-af97-c45a57fb1fab.png)

**Comment by Menci** [comment]
https://www.google.com/search?q=node-gyp+install+headers+offline

**Comment by EndstoneV** [comment]
打脸了 我把steam++关了就上来了

**Comment by EndstoneV** [comment]
status.nodejs.org可以了
nodejs.org还是不行

**Comment by EndstoneV** [comment]
这谷歌更打不开了……

**Comment by Menci** [comment]
那我觉得肯定是你的网的问题了 ……

谷歌应该不会这么容易 down

**Comment by Menci** [comment]
https://github.com/nodejs/node-gyp/issues/1154 试试参考一下这个

**Comment by EndstoneV** [comment]
Menci 在国内吗

**Comment by EndstoneV** [comment]
~~ 顺便，能通过群申请吗~~

**Comment by Menci** [comment]
*我不是群管理 不要找我*

**Comment by EndstoneV** [comment]
![image](https://user-images.githubusercontent.com/89293705/177483344-ce08cfca-0d79-44c2-b1a2-274912035853.png)
这又怎么了aaaaaa
configure error
