### ISSUE TITLE
Docker 搭建后局域网无法访问

### ISSUE THREAD

**Issue by EndstoneV** [syzoj/syzoj#255]
VMWare 虚拟机 Docker 搭建 syzoj 后局域网无法访问
我的设置：
```
env
SYZOJ_WEB_LISTEN=:::5283
```
其他全部按照教程复制粘贴。
我该如何做到让局域网其他机器可以访问？
*由于我比较蒻，所以我不想用 Nginx*

**Comment by starsky666** [comment]
您好，您的邮件已经收到！

**Comment by EndstoneV** [comment]
补充：

**Comment by EndstoneV** [comment]
补充：
浏览器显示：
无法访问此网站192.168.233.173 拒绝了我们的连接请求。

**Comment by EndstoneV** [comment]
：)

EndstoneV

发件人: ***@***.***>
发送时间: 2022年10月13日 13:40
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [syzoj/syzoj] Docker 搭建后局域网无法访问 (Issue #255)

您好，您的邮件已经收到！

―
