### ISSUE TITLE
Docker 搭建后时区无法设置

### ISSUE THREAD

**Issue by EndstoneV** [syzoj/syzoj#256]
如题，
![image](https://user-images.githubusercontent.com/89293705/197399822-8f6a24f6-de8d-4097-ab68-ab8adf679261.png)
不知道在哪里可以设置？范例文件里也没有 timezone 的设置

**Comment by Menci** [comment]
试一试给 syzoj 这个 service 加上环境变量？

```yaml
    environment:
      TZ: Asia/Tokyo
```
