### ISSUE TITLE
问题：始终 Wrong Answer

### ISSUE THREAD

**Issue by Sukwants** [syzoj/syzoj#263]
SYZOJ 搭好过后提交 C / C++ 它只会 Wrong Answer，直接 ``return 1;`` 和 ``while (1) ;`` 也会，感觉像是评测端的问题，能帮我解答一下吗？

测试点信息里，
Special Judge 信息：``Files user_out and answer differ``
系统信息：``Exited with return code 125（或者 126）``

C++、C、C++ (clang)、C （clang）都会出现上述情况，但是 C++ (NOI)、C (NOI) 和其他语言都可以评测。

我用的直接搭的方法，不是 docker。一切按照部署指南做的，只是 git 的部分我是直接下载 zip 包，只有这点与指南不同。

系统为 Ubuntu 22.04。

**Comment by starsky666** [comment]
您好，您的邮件已经收到！

**Comment by Sukwants** [comment]
用的直接搭的方法，没有用 docker

**Comment by Sukwants** [comment]
一切按照部署指南做的，只有 git 的部分是下载 zip 包这点不同。

服务器上除了 SYZOJ 还跑了一个 Samba。

**Comment by Sukwants** [comment]
应该是编译过程出锅了，评测端里把编译调用的 g++-8 换成 compile-cpp-noilinux 是可以跑的

**Comment by Sukwants** [comment]
测试了一下，C、C++、C (Clang)、C++ (Clang) 会出现上述问题，而 C (NOI)、C++ (NOI)、Pascal、Node.js、Python 3、Java、Haskell、C#、Ruby 则不会出现该问题。

前四者在 `judge/src/languages` 里的代码都是直接调用的 `gcc` / `g++` / ``clang`` / ``clang++``，后九者则调用的 ``compile-xxx``。

**Comment by Sukwants** [comment]
破案了，在 `config/runner-shared.json` 里面把 `DoNotUseX32ABI` 改成 `true` 就好了，应该是 Ubuntu 22.04 默认没有开启 32 位架构的原因。

希望能加入 [评测段部署指南](https://github.com/syzoj/syzoj/wiki/%E8%AF%84%E6%B5%8B%E7%AB%AF%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97) 里 [配置](https://github.com/syzoj/syzoj/wiki/%E8%AF%84%E6%B5%8B%E7%AB%AF%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#%E9%85%8D%E7%BD%AE) 部分，并加粗作为 **您很有可能需要修改的配置**。

打扰了。

**Comment by starsky666** [comment]
您好，您的邮件已经收到！
