### ISSUE TITLE
关于XSS的防御

### ISSUE THREAD

**Issue by zsxsoft** [syzoj/syzoj#3]
https://github.com/syzoj/syzoj/blob/b5fc7b92b94a3603ce06ee7c51e8f1246bf2138f/utility.js#L87

刚才又绕过了一下（→ https://loj.ac/ranklist

其实个人认为，这个防御规则还是太少了，用黑名单机制的话，事实上embed、object、iframe等一系列标签的危害也大到完全不应该出现在输出里。比如说embed来调用Flash、iframe来引用一些钓鱼网址之类的。绕过src过滤方法也挺多的，比如说data-uri系列、针对老版本IE的vbscript系列、我这次用的空白字符绕过系列，and so on...

个人想法是，使用白名单机制，或者只用Markdown=_=

推荐：https://github.com/leizongmin/js-xss

**Comment by Menci** [comment]
在你提这个 Issue 之前，我已经开始做白名单过滤了。

昨晚白名单过滤做好了，效果很好。

谢谢。
