### ISSUE TITLE
无法分别分配judge_server的内网和外网地址

### ISSUE THREAD

**Issue by hewenyang** [syzoj/syzoj#31]
使用场景：为了加快访问速度，judge_server应该配置为内网地址，例如http://127.0.0.1:5284
但是web端提供给客户端也必须是同样的地址，导致无法访问judge_server，无法实时获取评测结果。
可以考虑在web端提供judge_server的反向代理（个人更喜欢这项），或者在配置文件里分别配置内网地址和外网地址。

**Comment by Menci** [comment]
This should have been closed via #32.
