### ISSUE TITLE
能否添加一下代码是否公开的选项……

### ISSUE THREAD

**Issue by Wahacer** [syzoj/syzoj#53]
搭好OJ后用于自己学校使用……有些题可能会导致学弟学妹直接翻看提交记录……能否添加一个选项适用于某这道题是否公开代码……以及所有代码是否公开……
不过似乎有点违背loj的定义...

**Comment by goldimax** [comment]
我觉得是否公开在后台开选项是可以的……
// 重构参考

**Comment by fearlessxjdx** [comment]
你可以先用Nginx屏蔽下地址

**Comment by Menci** [comment]
否
