### ISSUE TITLE
是否可以打开关闭数据点下载功能?

### ISSUE THREAD

**Issue by fearlessxjdx** [syzoj/syzoj#54]
我没找到设置选项可以关闭数据点下载.
如果是作为校内OJ使用的话，我觉得还是需要在某些情况下关闭数据下载的。
如果没有这个功能的话，是否可以添加该功能？

**Comment by Chickking** [comment]
这样的功能可以自己魔改来实现吧……  
测试数据下载的 URL 很好抓吧，nginx 配置一下规则直接 `return 403;` 就是了。  
又不是什么麻烦的东西，而且 SYZOJ 本来就代表了一种开放共享的精神。  
个人感觉没有必要官方支持这一功能。

**Comment by Menci** [comment]
否
