### ISSUE TITLE
一个web服务是否可以连接多个judge服务?

### ISSUE THREAD

**Issue by fearlessxjdx** [syzoj/syzoj#62]
一个web服务是否可以连接多个judge服务?
应该怎么修改配置文件?
`"judge_server_addr": "http://127.0.0.1:5284",` 这里改吗? 怎么改?
redis和rabbitmq应该运行在web端还是judge端？

**Comment by Menci** [comment]
是

**Comment by Menci** [comment]
一个 judge daemon 可以有多个 judge runner

**Comment by fearlessxjdx** [comment]
> 一个 judge daemon 可以有多个 judge runner

用docker swarm的话 我应该replicas的是judge daemon吗?

**Comment by jyeric** [comment]
+1

**Comment by charliezcj** [comment]
@Menci +1

**Comment by memset0** [comment]
+1

**Comment by fearlessxjdx** [comment]
@Menci 配置多个 judge runner后似乎还是一道一道题评测的，并没有多道题同时评测。是否可以提供参考脚本？
