### ISSUE TITLE
Unable to open the "detailed deploying guide and a demo server"

### ISSUE THREAD

**Issue by littlepiggy03** [syzoj/syzoj#64]
<https://syzoj-demo.t123yh.xyz:20170/article/1>, which is referred in [the Deploying section in README](https://github.com/syzoj/syzoj#deploying).

**Comment by billchenchina** [comment]
The demo server has closed for certain reasons.
For support, please join LibreOJ 开发群（QQ：565280992 Telegram：https://t.me/lojdev ）

**Comment by littlepiggy03** [comment]
Thanks! It might helps a lot.
