### ISSUE TITLE
关于头像问题

### ISSUE THREAD

**Issue by BalanceUhen** [syzoj/syzoj#69]
根据LOJ上的文章，SYZOJ的头像更新之所以缓慢是因为头像的缓存，但是实际上已经几个月过去头像始终没有更新过。
看源码发现，LOJ使用gravatar.loli.net来加速获取头像的速度，但是因此出现了头像始终无法被更新的问题。
相反，我在挂代理亦或是不挂代理的情况下都可以正常使用Gravatar的头像，并且不会出现头像无法被更新的问题。
是否应该考虑放弃使用gravatar.loli.net来加速访问？（目前看来头像的更新不是慢的一星半点（甚至可能是基本不更新））

**Comment by Menci** [comment]
gravatar.loli.net 有一周的缓存
