### ISSUE TITLE
沙箱文件下载失败

### ISSUE THREAD

**Issue by lamhaoyin** [syzoj/syzoj#73]
如题。在执行以下命令时出错：
wget -O /sandbox-rootfs.tar.xz https://seafile.t123yh.xyz:2/seafhttp/files/38efbae3-887d-4ec8-b4f0-8f46625a708f/sandbox-rootfs-181202.tar.xz
HTTP 返回 400，浏览器提示 *Bad access token*

**Comment by jyeric** [comment]
https://seafile.t123yh.xyz:2/f/65f061a56f414b3db478/
自己下载

**Comment by t123yh** [comment]
新版沙箱为 https://seafile.t123yh.xyz:2/f/124a91be48ad41b98668/

**Comment by jyeric** [comment]
旧版沙箱被删除了？ @t123yh

**Comment by t123yh** [comment]
是的。@jyeric

**Comment by jyeric** [comment]
新版沙箱可以替代旧版沙箱吗？

**Comment by Menci** [comment]
最新版的沙箱与最新版的 judge-v3 兼容

**Comment by jyeric** [comment]
@Menci 那就行了，谢谢
