### ISSUE TITLE
Wiki内部沙箱文件MD5码没更新

### ISSUE THREAD

**Issue by interestingLSY** [syzoj/syzoj#74]
rt

```
md5sum /sandbox-rootfs.tar.xz 
09fe4fc407e4580e9ae4de8e2af5918e  /sandbox-rootfs.tar.xz
```

这个应该是对的

**Comment by interestingLSY** [comment]
@Menci

**Comment by Menci** [comment]
Fixed

**Comment by lybgy** [comment]
t-1
  
  
  
   发自189邮箱智能版
  
  
  
   
   ------------------ 原始邮件 ------------------
   
   发件人：Menci "notifications@github.com"
   时　间：2018/12/10 16:49:43 星期一
   收件人：syzojsyzoj "syzoj@noreply.github.com"
   抄送人：Subscribed "subscribed@noreply.github.com"
   主　题：Re: [syzoj/syzoj] Wiki内部沙箱文件MD5码没更新 (#74)
   
    
   Closed #74.
