### ISSUE TITLE
提交特定题目后后网页端崩溃

### ISSUE THREAD

**Issue by BalanceUhen** [syzoj/syzoj#75]
![image](https://user-images.githubusercontent.com/21274779/49721103-6f777e80-fc9c-11e8-8921-d84734a2ef5d.png)

emmmm, 提交某些题目之后网页端就崩掉了, 这是`nohup.out`的记录, 并不知道是什么原因, 但是这似乎是稳定触发的 (同一道题目只要提交`C/C++`代码就会崩溃)

**Comment by Menci** [comment]
是不是没有安装 clang-format？

**Comment by BalanceUhen** [comment]
好的，问题已经解决，也许应该更新一下网页端部署的WiKi内容？

**Comment by Menci** [comment]
已经更新了
