### ISSUE TITLE
无法按照通过率排序

### ISSUE THREAD

**Issue by BalanceUhen** [syzoj/syzoj#76]
![image](https://user-images.githubusercontent.com/21274779/49939598-419e6e00-ff18-11e8-8cbf-fbb6b04e48aa.png)
如图，可能因为`AC%`是在排序时计算的（我没在数据库里看到对应的列），然后发生了除以0的错误，所以这个排序选项虽然设置了，但是没法使用

**Comment by interestingLSY** [comment]
+1
