### ISSUE TITLE
按照Wiki部署会引起缺少部分数据表

### ISSUE THREAD

**Issue by Javi2004** [syzoj/syzoj#79]
http://oj.javiblog.top/

**Comment by woshiluo** [comment]
疑似并非wiki的问题，好像是初始化时有sql语法错误

**Comment by Javi2004** [comment]
所以我该怎么办呢？？？
# 惊恐万状.jpg
是不是在Wiki里**写**一下啊**！！！**

**Comment by BalanceUhen** [comment]
按照之前的issue来看，按照WiKi所下载MariaDB的版本应该是可以正常部署的，所以就没有再要求mysql的版本了。
<s>虽然我们一般电脑上都已经装好了一个MySQL</s>

**Comment by Javi2004** [comment]
然而我们用的是宝塔面板

**Comment by woshiluo** [comment]
> 然而我们用的是宝塔面板

 看看能不能更新`mysql`版本之类的
不行的话就选择抛弃面板或者使用旧版本吧 ...

**Comment by memset0** [comment]
> @Javi2004 
> 然而我们用的是宝塔面板

宝塔面板是可以的，你卸掉，重装的时候选 MariaDB 就好了。

~~不过为什么要用宝塔面板这种 Menci 硬点垃圾的面板呢 [可怜]~~

**Comment by Menci** [comment]
@woshiluo 直接安装 mairadb 10.3 即可自动转换原有数据格式。

如果你的 mysql 版本不被 mariadb 10.3 兼容，使用 `mysqldump` 导出，并在 mariadb 10.3 安装后恢复。
