### ISSUE TITLE
OLE request

### ISSUE THREAD

**Issue by billchenchina** [syzoj/syzoj#8]
详见 [15944](https://loj.ac/submission/15944)第一个测试点

**Comment by billchenchina** [comment]
[15947](https://loj.ac/submission/15947)直接AC了

**Comment by billchenchina** [comment]
刚刚注意到A+B是spj，或许是spj出了点问题？（雾

**Comment by Menci** [comment]
没有 OLE 是因为你输出的还不够多 ……

**Comment by billchenchina** [comment]
@Menci 不过输出的多了不是应该直接判OLE？
并不懂...（大雾

**Comment by billchenchina** [comment]
[15944](https://loj.ac/submission/15944)
且 2,3 测试点是 WA 而不是 OLE

**Comment by Menci** [comment]
输出的不够多啊
你输出个 100G 的文件你看它 OLE 不 OLE（雾

**Comment by Menci** [comment]
有 spj 的题是很难判「输出多了」的，比如有些人保留的小数位数比较多，就可能误判 OLE
现在的 OLE 判断方式是超过设定的一个较大的值判 OLE
