### ISSUE TITLE
wiki 添加请求

### ISSUE THREAD

**Issue by woshiluo** [syzoj/syzoj#81]
`Wiki` 有两点尚未说明,希望添加
- mysql 版本尚未详细说明 , 因为 `syzoj` 使用了`JSON`类型的数据,需要mysql(>=5.7)
> *值得一提的是,debian官方稳定源的mysql仍为5.5版本*
- `7zip`并不是所有系统都内置(比如说`Debian`) 但于 Wiki 中并未说明,`7zip`(或称`p7zip-full`)包的缺失会导致在上传数据是因调用不存在的解压命令而直接终止网页段进程

**Comment by Menci** [comment]
* 说明了 MariaDB 10.3
* 不提供 Debian 的官方支持

**Comment by jyeric** [comment]
是否可以直接写 TEXT NOT NULL
