### ISSUE TITLE
无法查看提交记录

### ISSUE THREAD

**Issue by BalanceUhen** [syzoj/syzoj#82]
![image](https://user-images.githubusercontent.com/21274779/50538786-13738c00-0bb0-11e9-9bed-65d51b45568f.png)

如图，可以看到，当一场比赛没有选手提交代码时查看提交记录出现了这种错误。

赛制：IOI
账户：**非权限账户**（使用管理员账号可以正常查看这个页面）

**Comment by Menci** [comment]
最近没什么时间修 bug ……
