### ISSUE TITLE
旧版本升级导致无法查看任何人的提交记录

### ISSUE THREAD

**Issue by jyeric** [syzoj/syzoj#83]
点击查看详细提交记录点入会出现以下错误
![failed.jpg](https://i.loli.net/2018/12/31/5c29ac976089e.jpg)
大体的提交记录能看 ![temp.jpg](https://i.loli.net/2018/12/31/5c29ad18abe6c.jpg)

**Comment by jyeric** [comment]
已升级 ALTER TABLE `user` ADD `prefer_formatted_code` TINYINT(1) NOT NULL AFTER `public_email`;

**Comment by jyeric** [comment]
https://github.com/syzoj/syzoj/commit/81cfeedf7b62f272ba0d6ab31d179d714b8563f1
是否将自己本地端进行这个修改就能~~**暂时**~~解决问题

**Comment by fearlessxjdx** [comment]
```bash
ALTER TABLE `user` ADD `prefer_formatted_code` TINYINT(1) NOT NULL DEFAULT 0 AFTER `public_email`;
```

**Comment by jyeric** [comment]
查看了，是新旧版本的锅。。。用的旧版的MySQL出的问题，升级到mariadb10.3就没有问题了
