### ISSUE TITLE
文本比较有时候会出现问题

### ISSUE THREAD

**Issue by BalanceUhen** [syzoj/syzoj#89]
如图，可以看到输出是不同的，但是被评判为相同并且给了分数，多个人提交都出现了同样的问题
![image](https://user-images.githubusercontent.com/21274779/51796410-de00a380-222c-11e9-99d1-e6f77eca4a5e.png)
如有需要可以提供测试数据

**Comment by BalanceUhen** [comment]
假如输出有换行是正常的，假如没有换行就会出现问题

**Comment by Menci** [comment]
此 Bug 已在 [sandbox-rootfs 版本 181202](https://github.com/syzoj/sandbox-rootfs/releases/tag/181202) 中修复。
请更新到最新版 syzoj，并使用最新版的 sandbox-rootfs。
