### ISSUE TITLE
Markdown的过滤还是不够

### ISSUE THREAD

**Issue by xmcp** [syzoj/syzoj#9]
## [点击此链接时请保证周围环境明亮](https://loj.ac/user/1146)

SYZOJ看起来对Markdown语法有白名单的限制，但我认为还应该增加对 `class`、`id`、`style` 的过滤。

在上面链接里的例子中，我把我的个性签名设置成了：

```html
<!-- magic background -->
<div style="
    background-image: url(http://s.xmcp.ml/doge.gif) !important; <!-- to override .ui.disabled.button -->
    background-repeat: repeat;
    top: -100vh; left: -100vw;
    height: 200vh; width: 200vw;
" class="
    morris-hover <!-- position: fixed -->
    ui disabled <!-- opacity: .45 -->
    circular images <!-- overflow: hidden -->
    button <!-- pointer-events: none -->
"></div>
```

从而起到了图片糊一屏幕的效果（如果做得再用心一点，甚至可以实现钓鱼攻击，比如放一个全屏的带链接的图片，说系统升级什么的，点击就会跳到假冒的钓鱼页面）。

值得注意地，虽然SYZOJ对 `position`、`overflow` 等高危 style 属性有过滤，但我们可以利用页面中的其他CSS绕过。比如这个：

![image](https://user-images.githubusercontent.com/6646473/28123897-c1ff83b6-6754-11e7-8f10-b1e139def974.png)

只要把我的 div 加上这个 `.morris-hover` 的 class，就自动获得了一个 `position: absolute;`，真是不得了。

另外，所有使用 Markdown 的页面中都有这个问题。比如说[帖子的页面](https://loj.ac/article/106)。

综上，建议 SYZOJ 限制 Markdown 中  `class`、`id`、`style` 三个属性的使用。

**Comment by xmcp** [comment]
现在在个人主页里可以通过一行 `<div id="pie_chart_legend"></div>` 实现把图例“拐跑”的效果。

![image](https://user-images.githubusercontent.com/6646473/28147147-281cd750-67b1-11e7-923a-17453cd99e79.png)

这是bug还是feature呢？:rofl:

**Comment by Menci** [comment]
噫 …… 似乎需要限制一下 id 的使用了 ……

**Comment by Menci** [comment]
Fixed with https://github.com/syzoj/syzoj/commit/fe4af1faf0aeae168f51b7175c25b405b7f9926f
