### ISSUE TITLE
上传数据包和导入题目时出现502 Bad Gateway

### ISSUE THREAD

**Issue by water-mi** [syzoj/syzoj#90]
在使用这个界面传数据包后转到502界面
![](https://s2.ax1x.com/2019/02/13/k0Bro8.png)
但是在测试数据界面选择上传数据就成功

然后导入题目只能导入题面不能导入数据

**Comment by Officeyutong** [comment]
安装p7zip

**Comment by water-mi** [comment]
谢了！此issue完结
